version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: hems-db
    environment:
      POSTGRES_DB: hems_emulator
      POSTGRES_USER: hems_user
      POSTGRES_PASSWORD: hems_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hems_user -d hems_emulator"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hems-backend
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://hems_user:hems_password@database:5432/hems_emulator
      JWT_SECRET: your_jwt_secret_key_change_in_production
      PORT: 3001
    volumes:
      - ./backend:/app
    depends_on:
      database:
        condition: service_healthy
    command: deno task dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hems-frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3001
      VITE_WS_URL: ws://localhost:3001
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: deno task dev

volumes:
  postgres_data: 