apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hems-emulator
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/memory: 2Gi
        run.googleapis.com/cpu: '2'
        run.googleapis.com/max-instances: '10'
        run.googleapis.com/min-instances: '1'
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/hems-emulator:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          value: "sqlite:///app/data/hems.db"  # Using SQLite for simplicity
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: hems-secrets
              key: jwt-secret
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10 